#!/usr/bin/env python3
"""Generate apps/build-image-pipeline.yml from registry.yml.

    python3 scripts/gen-image-pipeline.py           # write it
    python3 scripts/gen-image-pipeline.py --check    # CI: fail if it is stale

One build job and one sign job per app, following the pattern the repository
already used for the frontend image. The file is generated rather than written
by hand for one reason: the image tag in it must be the tag `registry.yml`
pins, and two hand-maintained copies of a version number diverge.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "apps" / "build-image-pipeline.yml"

HEADER = """\
# GENERATED by scripts/gen-image-pipeline.py — do not edit.
# One image per app. The tag comes from registry.yml, so the tag that CI builds
# and the tag that the deploy pins are the same string by construction.
#
# A job only runs when its own app changed. Eleven images rebuilt because one
# palette moved would be eleven chances for an unrelated failure.

"""


def blocks(instances: list[dict]) -> tuple[list, dict]:
    includes, jobs = [], {}
    for inst in instances:
        app, tag = inst["app"], inst["image_tag"]
        # harbor.example/dap-node-red/wag-prod:5.0.1-1 -> dap-node-red/wag-prod, 5.0.1-1
        path, _, version = tag.partition(":")
        image_name = "/".join(path.split("/")[1:])

        includes += [
            {"component": "$CI_SERVER_FQDN/infrastructure/ci-cd-catalog/buildah/buildah-build@~latest",
             "inputs": {"stage": "Build", "job_name": f"build:buildah:{app}",
                        "dockerfile": f"apps/{app}/Dockerfile", "image_name": image_name,
                        "enable_layers_cache": False}},
            {"component": "$CI_SERVER_FQDN/infrastructure/ci-cd-catalog/cosign/cosign-sign@~latest",
             "inputs": {"stage": "Sign", "job_name": f"sign:cosign:{app}",
                        "image_name": image_name}},
        ]
        rules = [{"if": '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH',
                  "changes": [f"apps/{app}/**/*"]}]
        jobs[f"build:buildah:{app}"] = {"variables": {"IMAGE_TAG": version}, "rules": rules}
        jobs[f"sign:cosign:{app}"] = {
            "variables": {"IMAGE_TAG": version},
            "needs": [{"job": f"build:buildah:{app}"}],
            "rules": rules,
        }
    return includes, jobs


class NoAliases(yaml.SafeDumper):
    """Emit every rules block in full.

    PyYAML would anchor the identical rule objects and alias the rest. GitLab
    understands anchors, but a reviewer reading `rules: *id009` cannot see what
    a job runs on without scrolling to find the anchor.
    """

    def ignore_aliases(self, data):
        return True


def render() -> str:
    registry = yaml.safe_load((ROOT / "registry.yml").read_text(encoding="utf-8"))
    instances = sorted((i for i in registry["instances"] if i.get("app")),
                       key=lambda i: i["app"])
    includes, jobs = blocks(instances)
    dump = lambda d: yaml.dump(d, Dumper=NoAliases, sort_keys=False, width=100)
    body = dump({"include": includes}) + "\n" + dump(jobs)
    return HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    want = render()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != want:
            print(f"{OUT} is stale — run: python3 scripts/gen-image-pipeline.py", file=sys.stderr)
            return 1
        print(f"{OUT.name} matches registry.yml")
        return 0

    OUT.write_text(want, encoding="utf-8")
    registry = yaml.safe_load((ROOT / "registry.yml").read_text(encoding="utf-8"))
    n = sum(1 for i in registry["instances"] if i.get("app"))
    print(f"wrote {OUT} — {n} images, one per app")
    return 0


if __name__ == "__main__":
    sys.exit(main())
