#!/usr/bin/env python3
"""Turn the collected samples into apps/<app>/ directories.

    python3 scripts/scaffold-apps.py

Reads `samples/*.flows.json` and `registry.yml`, and writes per app:

    apps/<app>/flows.json    the sample, normalized
    apps/<app>/Dockerfile    pinned to the Node-RED version that app runs
    apps/<app>/package.json  the palette, at the versions in use

The palette versions come from `inventory/<host>.json`, which is gitignored and
therefore only present on the machine that ran collect-inventory.py. Without it
the flows and Dockerfiles are still written and the missing package.json files
are listed, so a second run on that machine completes them.

Rerunnable: it overwrites what it generates and leaves anything else alone.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from normalize import normalize, render  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SAMPLES = ROOT / "samples"
INVENTORY = ROOT / "inventory"
APPS = ROOT / "apps"

# Node-RED reads its userDir from /data, which every instance bind-mounts — so a
# package.json baked into /data is hidden by the mount at runtime. Palette
# modules go into the application directory instead, where the runtime also
# looks and where no volume can shadow them.
DOCKERFILE = """\
# Generated by scripts/scaffold-apps.py — the Node-RED version is the one this
# instance already runs. Converging the estate on one version is a separate
# upgrade; see "Version spread" in docs/architecture.md.
FROM docker.io/nodered/node-red:{version}

# /data is bind-mounted at runtime, so palette modules are installed into the
# application directory instead — a package.json under /data would be shadowed
# by the mount.
#
# The path is repo-root relative because the buildah component builds with the
# repository as the context and passes only --file. Build it by hand the same
# way: docker build -f apps/{app}/Dockerfile .
COPY apps/{app}/package.json /usr/src/node-red/package.json
RUN npm install --no-audit --no-fund --no-update-notifier --omit=dev
"""


def load_palette(host: str, service: str) -> dict | None:
    """Exact palette versions for one instance, from the inventory report."""
    path = INVENTORY / f"{host}.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    for inst in data.get("instances", []):
        if inst.get("name") == service:
            palette = inst.get("palette") or {}
            return palette if isinstance(palette, dict) and "error" not in palette else {}
    return None


def node_red_version(host: str, service: str) -> str | None:
    path = INVENTORY / f"{host}.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    for inst in data.get("instances", []):
        if inst.get("name") == service:
            return inst.get("node_red_version") or None
    return None


def main() -> int:
    registry = yaml.safe_load((ROOT / "registry.yml").read_text(encoding="utf-8"))
    by_service = {
        (i["host"], i["compose_service"]): i
        for i in registry["instances"]
    }

    # Recorded so a machine without inventory/ still pins the right version.
    # Source: the Node-RED version column of the inventory report.
    FALLBACK_VERSION = {
        "cho-svr-lin01": "4.0.5", "gor-svr-lin01": "4.0.5",
        "jan-svr-lin01": "4.0.9", "slu-svr-lin02": "4.0.9",
        "srem-svr-lin01": "4.0.9", "wfm-svr-lin01": "4.0.9",
        "wag-svr-lin01": "5.0.1",
    }

    written, no_palette, unmatched = [], [], []

    for sample in sorted(SAMPLES.glob("*.flows.json")):
        host, _, service = sample.name[: -len(".flows.json")].partition("__")
        inst = by_service.get((host, service))
        if not inst or not inst.get("app"):
            unmatched.append(sample.name)
            continue

        app = APPS / inst["app"]
        app.mkdir(parents=True, exist_ok=True)

        nodes = json.loads(sample.read_text(encoding="utf-8"))
        (app / "flows.json").write_text(render(normalize(nodes)), encoding="utf-8")

        version = node_red_version(host, service) or FALLBACK_VERSION.get(host)
        if not version:
            print(f"{inst['app']}: no Node-RED version known", file=sys.stderr)
            return 1

        # The Dockerfile COPYs package.json, so the two are written together or
        # not at all — a Dockerfile without its package.json fails at build time
        # and would sit in the repo looking finished.
        palette = load_palette(host, service)
        if palette is None:
            no_palette.append(inst["app"])
        else:
            (app / "package.json").write_text(json.dumps({
                "name": f"node-red-{inst['app']}",
                "description": f"Palette for {inst['name']}",
                "private": True,
                "dependencies": dict(sorted(palette.items())),
            }, indent=2) + "\n", encoding="utf-8")
            (app / "Dockerfile").write_text(DOCKERFILE.format(version=version, app=inst["app"]), encoding="utf-8")

        written.append((inst["app"], len(nodes), version,
                        "?" if palette is None else str(len(palette))))

    print(f"{'app':<14} {'nodes':>6} {'node-red':>9} {'palette':>8}")
    print("-" * 42)
    for app, nodes, version, pal in written:
        print(f"{app:<14} {nodes:>6} {version:>9} {pal:>8}")

    if unmatched:
        print(f"\nNo registry entry, skipped: {', '.join(unmatched)}", file=sys.stderr)
    if no_palette:
        print(f"\n{len(no_palette)} app(s) have no package.json — inventory/ is not on this "
              f"machine, so the palette versions are unknown:\n  {', '.join(no_palette)}\n"
              f"Rerun this on the machine that ran collect-inventory.py.", file=sys.stderr)
        return 1

    print(f"\n{len(written)} apps written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
